# Setup
title: Jeremiah Boby
url: https://jerbob.me
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jeremiah Boby
  url: https://jerbob.me
  email: mail@jeremiahboby.me

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: /archive
    url: /archive

  - title: /about
    url: /about

  - title: /uses
    url: /2020/11/30/uses/
